##INICIAL

In [29]:
df = pd.read_csv('/content/train.csv')
display(df.head())

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,State,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales
0,1,CA-2017-152156,08/11/2017,11/11/2017,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,Kentucky,42420.0,South,FUR-BO-10001798,Furniture,Bookcases,Bush Somerset Collection Bookcase,261.9600
1,2,CA-2017-152156,08/11/2017,11/11/2017,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,Kentucky,42420.0,South,FUR-CH-10000454,Furniture,Chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",731.9400
2,3,CA-2017-138688,12/06/2017,16/06/2017,Second Class,DV-13045,Darrin Van Huff,Corporate,United States,Los Angeles,California,90036.0,West,OFF-LA-10000240,Office Supplies,Labels,Self-Adhesive Address Labels for Typewriters b...,14.6200
3,4,US-2016-108966,11/10/2016,18/10/2016,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,Florida,33311.0,South,FUR-TA-10000577,Furniture,Tables,Bretford CR4500 Series Slim Rectangular Table,957.5775
4,5,US-2016-108966,11/10/2016,18/10/2016,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,Florida,33311.0,South,OFF-ST-10000760,Office Supplies,Storage,Eldon Fold 'N Roll Cart System,22.3680

In [30]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9800 entries, 0 to 9799
Data columns (total 18 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Row ID         9800 non-null   int64
 1   Order ID       9800 non-null   object
 2   Order Date     9800 non-null   object
 3   Ship Date      9800 non-null   object
 4   Ship Mode      9800 non-null   object
 5   Customer ID    9800 non-null   object
 6   Customer Name  9800 non-null   object
 7   Segment        9800 non-null   object
 8   Country        9800 non-null   object
 9   City           9800 non-null   object
 10  State          9800 non-null   object
 11  Postal Code    9789 non-null   float64
 12  Region         9800 non-null   object
 13  Product ID     9800 non-null   object
 14  Category       9800 non-null   object
 15  Sub-Category   9800 non-null   object
 16  Product Name   9800 non-null   object
 17  Sales          9800 non-null   float64
dtypes: float64(2), int64(1), object(15)
memory usage: 1.3+ MB

In [31]:
display(df.describe())

            Row ID   Postal Code         Sales
count  9800.000000   9789.000000   9800.000000
mean   4900.500000  55273.322403    230.769059
std    2829.160653  32041.223413    626.651875
min       1.000000   1040.000000      0.444000
25%    2450.750000  23223.000000     17.248000
50%    4900.500000  58103.000000     54.490000
75%    7350.250000  90008.000000    210.605000
max    9800.000000  99301.000000  22638.480000

In [32]:
duplicate_rows = df.duplicated().sum()
print(f'Número de filas duplicadas: {duplicate_rows}')

Número de filas duplicadas: 0

### Valores únicos en columnas categóricas

In [33]:
for column in df.select_dtypes(include='object').columns:
    print(f'Column: {column}, Unique Values: {df[column].nunique()}')

Column: Order ID, Unique Values: 4922
Column: Order Date, Unique Values: 1230
Column: Ship Date, Unique Values: 1326
Column: Ship Mode, Unique Values: 4
Column: Customer ID, Unique Values: 793
Column: Customer Name, Unique Values: 793
Column: Segment, Unique Values: 3
Column: Country, Unique Values: 1
Column: City, Unique Values: 529
Column: State, Unique Values: 49
Column: Region, Unique Values: 4
Column: Product ID, Unique Values: 1861
Column: Category, Unique Values: 3
Column: Sub-Category, Unique Values: 17
Column: Product Name, Unique Values: 1849

### Valores únicos en columnas categóricas

In [34]:
for column in df.select_dtypes(include='object').columns:
    print(f'Column: {column}, Unique Values: {df[column].nunique()}')

Column: Order ID, Unique Values: 4922
Column: Order Date, Unique Values: 1230
Column: Ship Date, Unique Values: 1326
Column: Ship Mode, Unique Values: 4
Column: Customer ID, Unique Values: 793
Column: Customer Name, Unique Values: 793
Column: Segment, Unique Values: 3
Column: Country, Unique Values: 1
Column: City, Unique Values: 529
Column: State, Unique Values: 49
Column: Region, Unique Values: 4
Column: Product ID, Unique Values: 1861
Column: Category, Unique Values: 3
Column: Sub-Category, Unique Values: 17
Column: Product Name, Unique Values: 1849

In [35]:
print("\nValores únicos y conteo para 'Category':")
display(df['Category'].value_counts())

print("\nValores únicos y conteo para 'Region':")
display(df['Region'].value_counts())

print("\nValores únicos y conteo para 'Segment':")
display(df['Segment'].value_counts())

print("\nValores únicos y conteo para 'Ship Mode':")
display(df['Ship Mode'].value_counts())

Valores únicos y conteo para 'Category':

Category
Office Supplies    5909
Furniture          2078
Technology         1813
Name: count, dtype: int64

Valores únicos y conteo para 'Region':

Region
West       3140
East       2785
Central    2277
South      1598
Name: count, dtype: int64

Valores únicos y conteo para 'Segment':

Segment
Consumer       5101
Corporate      2953
Home Office    1746
Name: count, dtype: int64

Valores únicos y conteo para 'Ship Mode':

Ship Mode
Standard Class    5859
Second Class      1902
First Class       1501
Same Day           538
Name: count, dtype: int64

### Verificación de filas duplicadas

In [38]:
display(df.head())

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,State,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales
0,1,CA-2017-152156,08/11/2017,11/11/2017,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,Kentucky,42420.0,South,FUR-BO-10001798,Furniture,Bookcases,Bush Somerset Collection Bookcase,261.9600
1,2,CA-2017-152156,08/11/2017,11/11/2017,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,Kentucky,42420.0,South,FUR-CH-10000454,Furniture,Chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",731.9400
2,3,CA-2017-138688,12/06/2017,16/06/2017,Second Class,DV-13045,Darrin Van Huff,Corporate,United States,Los Angeles,California,90036.0,West,OFF-LA-10000240,Office Supplies,Labels,Self-Adhesive Address Labels for Typewriters b...,14.6200
3,4,US-2016-108966,11/10/2016,18/10/2016,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,Florida,33311.0,South,FUR-TA-10000577,Furniture,Tables,Bretford CR4500 Series Slim Rectangular Table,957.5775
4,5,US-2016-108966,11/10/2016,18/10/2016,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,Florida,33311.0,South,OFF-ST-10000760,Office Supplies,Storage,Eldon Fold 'N Roll Cart System,22.3680

In [39]:
display(df.describe())

            Row ID   Postal Code         Sales
count  9789.000000   9789.000000   9789.000000
mean   4896.705588  55273.322403    230.116193
std    2827.486899  32041.223413    625.302079
min       1.000000   1040.000000      0.444000
25%    2449.000000  23223.000000     17.248000
50%    4896.000000  58103.000000     54.384000
75%    7344.000000  90008.000000    210.392000
max    9800.000000  99301.000000  22638.480000

In [ ]:
import pandas as pd

In [40]:
duplicate_rows = df.duplicated().sum()
print(f'Número de filas duplicadas: {duplicate_rows}')

Número de filas duplicadas: 0

### Manejo de Valores Nulos

In [ ]:
print('Valores nulos por columna:')
display(df.isnull().sum())

Valores nulos por columna:

Row ID            0
Order ID          0
Order Date        0
Ship Date         0
Ship Mode         0
Customer ID       0
Customer Name     0
Segment           0
Country           0
City              0
State             0
Postal Code      11
Region            0
Product ID        0
Category          0
Sub-Category      0
Product Name      0
Sales             0
dtype: int64

### Conversión de Tipos de Datos (Fechas)

In [ ]:
df['Order Date'] = pd.to_datetime(df['Order Date'], format='%d/%m/%Y')
df['Ship Date'] = pd.to_datetime(df['Ship Date'], format='%d/%m/%Y')
print('\nTipos de datos después de la conversión de fechas:')
df.info()

Tipos de datos después de la conversión de fechas:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9800 entries, 0 to 9799
Data columns (total 18 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Row ID         9800 non-null   int64
 1   Order ID       9800 non-null   object
 2   Order Date     9800 non-null   datetime64[ns]
 3   Ship Date      9800 non-null   datetime64[ns]
 4   Ship Mode      9800 non-null   object
 5   Customer ID    9800 non-null   object
 6   Customer Name  9800 non-null   object
 7   Segment        9800 non-null   object
 8   Country        9800 non-null   object
 9   City           9800 non-null   object
 10  State          9800 non-null   object
 11  Postal Code    9789 non-null   float64
 12  Region         9800 non-null   object
 13  Product ID     9800 non-null   object
 14  Category       9800 non-null   object
 15  Sub-Category   9800 non-null   object
 16  Product Name   9800 non-null   object
 17  Sales          9800 non-null   float64
dtypes: datetime64[ns](2), float64(2), int64(1), object(13)
memory usage: 1.3+ MB

## FINAL

In [24]:
df_clean = pd.read_csv('/content/train_clean.csv')
print('Dataset `train_clean.csv` cargado exitosamente.')

Dataset `train_clean.csv` cargado exitosamente.

### Estructura y Tipos de Datos de `df_clean`

Confirmamos la estructura del DataFrame y los tipos de datos del dataset limpio.

In [25]:
df_clean.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9800 entries, 0 to 9799
Data columns (total 26 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Row ID           9800 non-null   int64
 1   Order ID         9800 non-null   object
 2   Order Date       9800 non-null   object
 3   Ship Date        9800 non-null   object
 4   Ship Mode        9800 non-null   object
 5   Customer ID      9800 non-null   object
 6   Customer Name    9800 non-null   object
 7   Segment          9800 non-null   object
 8   Country          9800 non-null   object
 9   City             9800 non-null   object
 10  State            9800 non-null   object
 11  Postal Code      9800 non-null   object
 12  Region           9800 non-null   object
 13  Product ID       9800 non-null   object
 14  Category         9800 non-null   object
 15  Sub-Category     9800 non-null   object
 16  Product Name     9800 non-null   object
 17  Sales            9800 non-null   float64
 18  Year             9800 non-null   int64
 19  Month            9800 non-null   int64
 20  Month Name       9800 non-null   object
 21  Nivel_Ventas     9800 non-null   object
 22  Month_Name       9800 non-null   object
 23  Quarter          9800 non-null   object
 24  Region_Category  9800 non-null   object
 25  Shipping_Time    9800 non-null   int64
dtypes: float64(1), int64(4), object(21)
memory usage: 1.9+ MB

### Valores Nulos en `df_clean`

Verificamos la presencia de valores nulos en el dataset limpio.

In [26]:
print('Valores nulos por columna en df_clean:')
display(df_clean.isnull().sum())

Valores nulos por columna en df_clean:

Row ID             0
Order ID           0
Order Date         0
Ship Date          0
Ship Mode          0
Customer ID        0
Customer Name      0
Segment            0
Country            0
City               0
State              0
Postal Code        0
Region             0
Product ID         0
Category           0
Sub-Category       0
Product Name       0
Sales              0
Year               0
Month              0
Month Name         0
Nivel_Ventas       0
Month_Name         0
Quarter            0
Region_Category    0
Shipping_Time      0
dtype: int64

### Primeras Filas de `df_clean`

Visualizamos las primeras filas del DataFrame `df_clean`.

In [27]:
display(df_clean.head())

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,...,Product Name,Sales,Year,Month,Month Name,Nivel_Ventas,Month_Name,Quarter,Region_Category,Shipping_Time
0,1,CA-2017-152156,2017-11-08,2017-11-11,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,Bush Somerset Collection Bookcase,261.9600,2017,11,November,Alto,November,2017Q4,South - Furniture,3
1,2,CA-2017-152156,2017-11-08,2017-11-11,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",731.9400,2017,11,November,Alto,November,2017Q4,South - Furniture,3
2,3,CA-2017-138688,2017-06-12,2017-06-16,Second Class,DV-13045,Darrin Van Huff,Corporate,United States,Los Angeles,...,Self-Adhesive Address Labels for Typewriters b...,14.6200,2017,6,June,Bajo,June,2017Q2,West - Office Supplies,4
3,4,US-2016-108966,2016-10-11,2016-10-18,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,Bretford CR4500 Series Slim Rectangular Table,957.5775,2016,10,October,Alto,October,2016Q4,South - Furniture,7
4,5,US-2016-108966,2016-10-11,2016-10-18,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,Eldon Fold 'N Roll Cart System,22.3680,2016,10,October,Bajo,October,2016Q4,South - Office Supplies,7

Obtenemos las estadísticas descriptivas de las columnas numéricas en `df_clean`.

In [28]:
display(df_clean.describe())

            Row ID         Sales         Year        Month  Shipping_Time
count  9800.000000   9800.000000  9800.000000  9800.000000    9800.000000
mean   4900.500000    230.769059  2016.724184     7.818469       3.961122
std    2829.160653    626.651875     1.123984     3.281905       1.749614
min       1.000000      0.444000  2015.000000     1.000000       0.000000
25%    2450.750000     17.248000  2016.000000     5.000000       3.000000
50%    4900.500000     54.490000  2017.000000     9.000000       4.000000
75%    7350.250000    210.605000  2018.000000    11.000000       5.000000
max    9800.000000  22638.480000  2018.000000    12.000000       7.000000